package com.uuauth.ams.domain.entity;

/**
 * EmployeeRole generated by MyEclipse - Hibernate Tools
 */
public class EmployeeRole implements java.io.Serializable {
	// Fields
	
	/**  */
	private static final long	serialVersionUID	= 4529002119575713076L;
	/**
        *
        */
	private Long				id;
	private Integer				empId;
	private String				proToken;
	private String				roleName;
	
	// Constructors
	
	/** default constructor */
	public EmployeeRole() {
		//
	}
	
	/** minimal constructor */
	public EmployeeRole(Long id) {
		this.id = id;
	}
	
	/** full constructor */
	public EmployeeRole(Long id, Integer empId, String proToken, String roleName) {
		this.id = id;
		this.empId = empId;
		this.proToken = proToken;
		this.roleName = roleName;
	}
	
	// Property accessors
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}
	
	public Integer getEmpId() {
		return this.empId;
	}
	
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}
	
	public String getProToken() {
		return this.proToken;
	}
	
	public void setProToken(String proToken) {
		this.proToken = proToken;
	}
	
	public String getRoleName() {
		return this.roleName;
	}
	
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}
