package com.uuauth.ams.domain.entity;

/**
 * EmployeeLog generated by MyEclipse Persistence Tools
 */
public class EmployeeLog implements java.io.Serializable {
	
	// Fields
	
	/**  */
	private static final long	serialVersionUID	= 4304299606280610752L;
	private Integer				id;
	private Integer				operator;
	private Integer				logtime;
	private String				ip;
	private String				description;
	private String				object;
	private Integer				type;
	
	// Constructors
	
	/** default constructor */
	public EmployeeLog() {
		//
	}
	
	/** minimal constructor */
	public EmployeeLog(Integer id) {
		this.id = id;
	}
	
	/** full constructor */
	public EmployeeLog(Integer id, Integer operator, Integer logtime,
			String ip, String description, String object, Integer type) {
		this.id = id;
		this.operator = operator;
		this.logtime = logtime;
		this.ip = ip;
		this.description = description;
		this.object = object;
		this.type = type;
	}
	
	// Property accessors
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getOperator() {
		return this.operator;
	}
	
	public void setOperator(Integer operator) {
		this.operator = operator;
	}
	
	public Integer getLogtime() {
		return this.logtime;
	}
	
	public void setLogtime(Integer logtime) {
		this.logtime = logtime;
	}
	
	public String getIp() {
		return this.ip;
	}
	
	public void setIp(String ip) {
		this.ip = ip;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getObject() {
		return this.object;
	}
	
	public void setObject(String object) {
		this.object = object;
	}
	
	public Integer getType() {
		return this.type;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}
	
}