package com.uuauth.ams.domain.entity;

/**
 * ProjectLog generated by MyEclipse - Hibernate Tools
 */
public class ProjectLog implements java.io.Serializable {
	// Fields
	
	/**  */
	private static final long	serialVersionUID	= 4572616425281724579L;
	/**
        *
        */
	private Long				id;
	private Integer				empId;
	private String				ip;
	private Integer				logTime;
	private Integer				type;
	private String				description;
	private String				proToken;
	
	// Constructors
	
	/** default constructor */
	public ProjectLog() {
		//
	}
	
	/** minimal constructor */
	public ProjectLog(Long id) {
		this.id = id;
	}
	
	/** full constructor */
	public ProjectLog(Long id, Integer empId, String ip, Integer logTime,
			Integer type, String description, String proToken) {
		this.id = id;
		this.empId = empId;
		this.ip = ip;
		this.logTime = logTime;
		this.type = type;
		this.description = description;
		this.proToken = proToken;
	}
	
	// Property accessors
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}
	
	public Integer getEmpId() {
		return this.empId;
	}
	
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}
	
	public String getIp() {
		return this.ip;
	}
	
	public void setIp(String ip) {
		this.ip = ip;
	}
	
	public Integer getLogTime() {
		return this.logTime;
	}
	
	public void setLogTime(Integer logTime) {
		this.logTime = logTime;
	}
	
	public Integer getType() {
		return this.type;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getProToken() {
		return this.proToken;
	}
	
	public void setProToken(String proToken) {
		this.proToken = proToken;
	}
}
