package com.uuauth.ams.domain.entity;

import java.util.HashMap;
import java.util.Map;

/**
 * RoleTemplate generated by MyEclipse - Hibernate Tools
 */
public class TemplateRole implements java.io.Serializable {
	// Fields
	
	/**  */
	private static final long			serialVersionUID	= 713297752509278621L;
	/**
        *
        */
	private Integer						id;
	private String						templateName;
	private String						contentList;
	public static Map<Integer, String>	list				= new HashMap<Integer, String>();
	
	// Constructors
	
	/** default constructor */
	public TemplateRole() {
		//
	}
	
	/** minimal constructor */
	public TemplateRole(Integer id) {
		this.id = id;
	}
	
	/** full constructor */
	public TemplateRole(Integer id, String templateName) {
		this.id = id;
		this.templateName = templateName;
	}
	
	// Property accessors
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getTemplateName() {
		return this.templateName;
	}
	
	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}
	
	public String getContentList() {
		return this.contentList;
	}
	
	public void setContentList(String contentList) {
		this.contentList = contentList;
	}
	
}
